name: api_architecture
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  bearer_token_package: ^1.0.1
  dart_frog: ^1.0.0
  supabase: ^2.2.5

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
